### ISSUE TITLE
Cách detect chữ dọc hiệu suất cao

### ISSUE THREAD

**Issue by leviethung2103** [18520339/vietnamese-nom-script#2]
Cảm ơn tác giả vì đã tạo repo rất có ý nghĩa này,

Mình có câu hỏi muốn nhờ tác giả giải đáp dùm.

Theo mình biết thì model PaddleOCR - Text Detection nhận dạng tốt cho những hàng ngang. Nhưng đa số trong cái bài học thì chữ hàng dọc. Trong phần README có đề cập đến việc xoay ảnh. 

Thì mình muốn biết cụ thể phương pháp ở đây là gì ạ ? Xoay ảnh trái hay xoay ảnh phải. Cách training như thế nào cho model text detection và text recognition. Ảnh mình training cho text recognition model cũng là ảnh xoay luôn đúng không ạ ?

**Comment by 18520339** [comment]
Ban đầu mình làm cũng có thắc mắc như bạn. Nguyên do là mình đã bị ràng buộc bởi những kiến thức đã biết nên ko hiểu những thứ diễn ra dưới góc nhìn của máy tính. Làm sao để model mình hiểu chữ dọc trong khi các model phổ biến trên thị trường toàn train trên chữ ngang?

Thực ra xét cho cùng thì ngang hay dọc ko phải thứ model quan tâm mà là các đặc trưng trong ảnh. Vậy nên xoay kiểu nào cũng ko quan trọng, miễn khi inference mình cung cấp đầu vào được xoay tương ứng như khi mình huấn luyện là được. 

Mình lấy 1 ví dụ cho dễ hiểu, mình sẽ lấy na ná cho bạn dễ hình dung các kí tự khi xoay -90 độ của dòng chữ "CHU NOM" như sau: C (U), H(I), U(⊃), N(Z), O(O), M(∑). Như vậy "CHU NOM" khi xoay -90 sẽ thành "UI⊃ ZO∑". Khi huấn luyện, mình chỉ cần báo cho model biết ảnh "UI⊃ ZO∑" này có nhãn nó là "CHU NOM". Như vậy khi dự đoán, model cũng hiểu tương tự 1 ảnh có các đặc trưng của "UI⊃ ZO∑" thì sẽ chứa các kí tự C,H,U, ,N,O,M

**Comment by 18520339** [comment]
Ban đầu mình làm cũng có thắc mắc như bạn. Nguyên do là mình đã bị ràng buộc bởi những kiến thức đã biết nên ko hiểu những thứ diễn ra dưới góc nhìn của máy tính. Làm sao để model mình hiểu chữ dọc trong khi các model phổ biến trên thị trường toàn train trên chữ ngang?

Thực ra xét cho cùng thì ngang hay dọc ko phải thứ model quan tâm mà là các đặc trưng trong ảnh. Vậy nên xoay kiểu nào cũng ko quan trọng, miễn khi inference mình cung cấp đầu vào được xoay tương ứng như khi mình huấn luyện là được. 

Mình lấy 1 ví dụ cho dễ hiểu, mình sẽ lấy na ná cho bạn dễ hình dung các kí tự khi xoay -90 độ của dòng chữ "CHU NOM" như sau: C ~ U, H ~ ≠, U ~ ⊃, N ~ Z, O ~ O, M ~ ∑. Như vậy "CHU NOM" khi xoay -90 sẽ thành "U≠⊃ ZO∑" (Bạn có thể nghiêng đầu qua trái coi thấy giống ko 🤣). Khi huấn luyện, mình chỉ cần báo cho model biết ảnh "U≠⊃ ZO∑" này có nhãn là "CHU NOM". Như vậy khi dự đoán, model cũng hiểu tương tự 1 ảnh có các đặc trưng của "U≠⊃ ZO∑" thì sẽ chứa các kí tự C,H,U, ,N,O,M

**Comment by leviethung2103** [comment]
Cảm ơn tác giả nhé. Mình đã hiểu rồi ^^
