### ISSUE TITLE
Link của weights trên Google Drive không thể truy cập được

### ISSUE THREAD

**Issue by DongKat** [18520339/vietnamese-nom-script#3]
Cảm ơn tác giả đã bỏ công sức vào xây dựng công trình này.
Mình muốn chạy thử nghiệm các mô hình detection và recognition, không biết bên tác giả có thể tạo link mới tới weights được không vậy?

**Comment by 18520339** [comment]
Đây bạn nhé, do GDrive mình bị bóp nên mình move sang chỗ khác
https://drive.google.com/file/d/1GDUM3gO5hDBaicCbESf3G07XH5I3sx4k/view?usp=sharing

**Comment by DongKat** [comment]
Cảm ơn tác giả nhiều

**Comment by DongKat** [comment]
Cảm ơn tác giả đã chia sẻ weights các mô hình. Tuy nhiên, mình không thể load mô hình CNNxSeq2Seq. Mong tác giả có thể giúp mình với lỗi này.

![Screenshot 2024-05-30 111658](https://github.com/ds4v/NomNaOCR/assets/81170722/4c2a9fa9-855b-4fe9-8333-ccf9414298c8)

Còn đây là summary mô hình Decoder trong notebook

    Model: "Decoder"
        _____________________________________________________________________________________________________________________________
        Layer (type)                        Output Shape                          Param #     Connected to                          
        =============================================================================================================================
        new_token (InputLayer)              [(None, 1)]                           0           []                                    
                                                                                                                                    
        embedding (Embedding)               (None, 1, 512)                        3831296     ['new_token[0][0]']                   
                                                                                                                                    
        previous_state (InputLayer)         [(None, 512)]                         0           []                                    
                                                                                                                                    
        dec_gru (GRU)                       [(None, 1, 512),                      1575936     ['embedding[0][0]',                   
                                            (None, 512)]                                      'previous_state[0][0]']              
                                                                                                                                    
        encoder_sequence (InputLayer)       [(None, 25, 512)]                     0           []                                    
                                                                                                                                    
        AdditiveAttention (AdditiveAttenti  ((None, 1, 512),                      524800      ['dec_gru[0][0]',                     
        on)                                  (None, 1, 25))                                    'encoder_sequence[0][0]']            
                                                                                                                                    
        tf.concat (TFOpLambda)              (None, 1, 1024)                       0           ['AdditiveAttention[0][0]',           
                                                                                                'dec_gru[0][0]']                     
                                                                                                                                    
        attention_vector (Dense)            (None, 1, 512)                        524288      ['tf.concat[0][0]']                   
                                                                                                                                    
        flatten (Flatten)                   (None, 512)                           0           ['attention_vector[0][0]']            
                                                                                                                                    
        prediction (Dense)                  (None, 7483)                          3838779     ['flatten[0][0]']                     
                                                                                                                                    
        =============================================================================================================================
        Total params: 10295099 (39.27 MB)
        Trainable params: 10295099 (39.27 MB)
        Non-trainable params: 0 (0.00 Byte)
        _____________________________________________________________________________________________________________________________

**Comment by 18520339** [comment]
Mình cũng vừa check thử weights decoder, có vẻ trong lúc lưu thì team mình đã lưu đè nhầm weights thuộc 1 version cũ hơn của model này. Trường hợp này chắc bạn phải train lại decoder thôi. Còn nếu bạn chỉ quan tâm kết quả mình thống kê thì nó vẫn đúng nhé, ko bị ảnh hưởng.
